feat: make the action work (#6)
* style: remove spaces on empty lines

* refactor: change wordir for the one mounted by github

* feat: fill action.yaml

* feat: change entrypoint to run sw

* refactor: change lang parameter to match sw's cli input

* test: write test for the action (untested)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,11 +44,34 @@ jobs:
           push: true
           tags: ${{ env.TEST_TAG }}
 
+      - name: Pull tests
+        id: tests
+        uses: actions/checkout@v4
+        with:
+          repository: jobtrek/sw
+          ref: v0.1.4
+
       - name: Run the Container
         id: run
         env:
-          INPUT_WHO_TO_GREET: Mona Lisa Octocat
+          INPUT_PATH: "test/test"
+          INPUT_LANG: "rs,js,ts"
         run: |
           docker run \
-            --env INPUT_WHO_TO_GREET="${{ env.INPUT_WHO_TO_GREET }}" \
-            --rm ${{ env.TEST_TAG }}
+            --volume ${{ github.workspace }}:/github/workspace \
+            --env INPUT_PATH="$INPUT_PATH" \
+            --env INPUT_LANG="$INPUT_LANG" \
+            --rm \
+            ${{ env.TEST_TAG }}
+
+      - name: Test if the test passed
+        id: check
+        run: |
+          tree test
+          if diff -rq test/test test/expected; then
+            echo "Test passed"
+          else
+            echo "Test failed"
+            diff -r test/test test/expected
+            exit 1
+          fi
